### Variables globales
@baseUrl = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NWM2NDJiNTA4NzJhMTYwNGU0NWM5MCIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc1MDg4NTY3NywiZXhwIjoxNzUwOTcyMDc3fQ.8VmSZdAZbB9HWmSoNvVL-1JaqVdQ68Rg0y4NguJghMc
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NWM2N2Q2NzYwOGZkMTJjN2EyYzBlZSIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTA4ODYzNTgsImV4cCI6MTc1MDk3Mjc1OH0.GmdISTzIkPX2-JqFKbizPm3vsE3AbomWbCOYTIfusjM

@userId = 685c671e7608fd12c7a2c0df

### Obtener todos los usuarios (solo admin)
GET {{baseUrl}}/api/users HTTP/1.1
Authorization: Bearer {{adminToken}}

### Obtener usuario por ID (requiere autenticación, solo el propio usuario o admin)
GET {{baseUrl}}/api/users/{{userId}} HTTP/1.1
Authorization: Bearer {{token}}

### Actualizar usuario (requiere autenticación, solo el propio usuario o admin)
PUT {{baseUrl}}/api/users/{{userId}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Smith",
  "age": 31,
  "address": {
    "street": "123 Main St",
    "city": "New York",
    "zip": "10001",
    "country": "USA"
  }
}

### Eliminar usuario (solo admin)
DELETE {{baseUrl}}/api/users/{{userId}}
Authorization: Bearer {{adminToken}}
